spring:
  application:
    name: t1-task-service
  datasource:
    url: jdbc:postgresql://localhost:15432/task_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8001
  error:
    include-message: always

kafka:
  server: kafka:29092
  session-timeout: 15000
  max-partition-fetch-bytes: 300000
  max-poll-records: 1
  max-poll-interval: 3000
  topic: task_update_notifications
  group-id: t1-task-service
  producer-enable: true